print('          _______')
print('         / o      \ ')
print('     ___|_____     |___')
print('    /              |   \ ')
print('   /      ________/     \ ')
print('   \     /              /')
print('    \___/      ________/')
print('        |       o |')
print('         \_______/')
print('       Python Logo')
print('     by Brandon Dols')