print('WELCOME TO:\nWinter Wonderland Mad Libs')
print('\nLet\'s begin!')
adj1 = input("Enter an adjective: ").lower()
adj2 = input("Enter another adjective: ").lower()
col1 = input('Enter a color: ').lower()
verb1 = input('Enter a verb: ').lower()
adj3 = input('Enter an adjective: ').lower()
veg1 = input('Enter a vegetable: ').lower()
exl1 = input('Enter an exclamation (e.g. yikes): ').capitalize()
verb2 = input('Enter an \'ing\' verb (e.g. running): ').lower()
verb3 = input('Enter another \'ing\' verb: ').lower()
noun1 = input('Enter a noun: ').lower()
verb4 = input('Enter a verb: ').lower()
place1 = input('Enter a place: ').lower()
adj4 = input('Enter an adjective: ').lower()
num1 = input('Enter a number: ').lower()
noun2 = input('Enter a plural noun: ').lower()
body_part1 = input('Enter a body-part: ').lower()
body_part2 = input('Enter another body-part: ').lower()
veg2 = input('Enter a vegetable: ').lower()
name1 = input('Enter a name: ').lower().capitalize()
exl2 = input('Enter an exclamation: ').capitalize()

# print mad lib
print(f'\n\nHere is your Winter Mad Lib:\n\nMr. {name1} the Snowman\n')
print(f'Let\'s build a snowman! First we need to')
print(f'have a really {adj1} snowstorm,')
print(f'of course, on a {adj2} day. Watching')
print(f'all that {col1} snow fall makes me {verb1}')
print(f'for a bowl of {adj3} {veg1} soup. {exl1}! It\'s still')
print(f'{verb2} and there\'s a lot of it. Let\'s go!')
print(f'Next is {verb3} to go out in the cold.')
print(f'Once that\'s done we need to get busy.')
print(f'We make a {noun1} and {verb4} it in the')
print(f'{place1}. It gets so {adj4} we can\'t roll it anymore.')
print(f'Then we do {num1} more and stack them on')
print(f'top of each other. We look for {noun2} in')
print(f'the driveway for the {body_part1}, eyes and {body_part2}.')
print(f'Mom gives us a scarf, hat and {veg2} to')
print(f'complete Mr. {name1}. {exl2}! He\'s done!')